name: Publish to JSR
on:
  push:
    tags:        
      - '*'  # Publish every time a tag is pushed (unless it contains '/')

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish
